default_stages: [pre-commit]

repos:
# Ruff
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        description: "Run 'ruff check' for extremely fast Python linting"
        entry: uv run ruff check --config=pyproject.toml
        args: [--fix]
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: uv run ruff format --config=pyproject.toml
        language: system
        types: [python]

# ty
  - repo: local
    hooks:
      - id: ty
        name: ty
        description: "Run 'ty' for Python type checking using settings from pyproject.toml"
        entry: uv run ty check wandas tests
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true

ci:
  autoupdate_schedule: weekly
